### ISSUE TITLE
get result from few merchants

### ISSUE THREAD

**Issue by sasikanth513** [robogeek/skimlinksjs#1]
I want results from Amazon and target only . I tried like this,looks like it is not working

var result = skimlinks_query({
                searchFor: "title:\"electric bicycle\" isAccessory:false merchant:(Amazon OR Target)",
                fq: "country:US"
                });
I'm getting results from all merchants like(buy ,NewEgg..etc)

**Comment by robogeek** [comment]
There is a developers mailing list for the Skimlinks API ...

I'd had lots of trouble getting good queries using my library - went to
that mailing list - and got no answers - so had given up on developing this
library further.
- David

**Comment by sasikanth513** [comment]
Do u have mail id to contact them regarding these issues??
